#!/usr/bin/env bash
# if_9_say_hi: display Hi on 9th Iteration.

count=1

while [[ "$count" -le 10 ]]; do
  echo "Best School"
  if [ "$count" -eq 9 ]; then
    echo "Hi"
  fi
  count=$((count + 1))
  done

