#!/usr/bin/env bash
# 4_bad_luck_8_is_your_chance: displays bad luck for the 4th loop iteration,
# displays good luck for the 8th loop iteration,
# displays Best School for the other iterations

count=1

while [[ "$count" -le 10 ]]; do
	if [ "$count" -eq 4 ]; then
		echo "bad luck"
		count=$((count + 1))
	elif [ "$count" -eq 8 ]; then
		echo "good luck"
		count=$((count + 1))
	else
		echo "Best School"
		count=$((count + 1))
	fi
	done
