#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
minutes=0
echo "Hours : $hours"
while [[ "$hours" -le 12 ]]; do
  if [ "$hours" -ge 12 ]; then
    if [ "$minutes" -eq 59 ]; then
      exit
    fi
  fi

  minutes=$((minutes + 1))
  if [ "$minutes" -eq 60 ]; then
    hours=$((hours + 1))
    echo "Hours : $hours"
    minutes=1
  fi
  echo "$minutes"
done

